### ISSUE TITLE
Create a PushPlatformValidationSimulation

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-gatling#111]
### Objective

Adapts existing platform validation to the PUSH

### How

- Modify the current PlatformValidation scenario, adding the Mailbox, Email/changes steps that we created in #110
- Recalibrate the randomSwitch() possibilities so that it better reflects the real user interaction in Mailbox/Email synchronization scenario.

### DoD

- New PushPlatformValidationScenario passing all the checks.

**Comment by Arsnael** [comment]
Open websocket per user and enable push -> prepare step
Add /changes
=> new push simulation

**Comment by chibenwa** [comment]
## Remaining work for Create a PushPlatformValidationSimulation#111

As of 10/05 we remain to...

 - Rebase https://github.com/linagora/james-gatling/pull/118
 - Reduce the calls to getMailboxes in the prepare stage (4 in total we should get it down to one as in https://github.com/linagora/james-gatling/pull/116)
 - Rework https://github.com/apache/james-project/pull/422
