### ISSUE TITLE
IMAP platform validation should be more relevant

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-gatling#133]
Following https://github.com/linagora/james-project-private/issues/383

Adapt IMAP simulation to better reflect reality. Add missing IMAP commands to Gatling-IMAP if need be!

**Comment by chibenwa** [comment]
- [x] Gatling IMAP should support `status`

Example:

```
33 STATUS "test" (UIDNEXT MESSAGES UNSEEN RECENT)
* STATUS "test" (MESSAGES 0 RECENT 0 UIDNEXT 1 UNSEEN 0)
33 OK STATUS completed.
```

 - [x] Gatling IMAP should support `capability`

Example:

```
4 capability
* CAPABILITY NAMESPACE SEARCHRES QRESYNC UNSELECT ACL ENABLE QUOTA SASL-IR WITHIN CHILDREN UIDPLUS AUTH=PLAIN IDLE LITERAL+ I18NLEVEL=1 MOVE IMAP4REV1 ESEARCH ANNOTATION
4 OK CAPABILITY completed.
```

 - [x] Gatling IMAP should support `enable`

Example:

```
7 ENABLE UTF8=ACCEPT
* ENABLED
7 OK ENABLE completed
```

 - [x] Gatling IMAP should support `getquotaroot`

Example:

```
9 getquotaroot "INBOX"
* QUOTAROOT "INBOX" #private&user@domain.org
9 OK GETQUOTAROOT completed.
```

 - [x] Gatling IMAP should support `myrights`

Example:

```
24 myrights "test"
* MYRIGHTS "test" "aeiklprstwx"
24 OK MYRIGHTS completed.`
```

 - [x] Gatling IMAP should support `getacl`

```
25 getacl "test"
* ACL "test" "owner" "aeiklprstwx"
25 OK GETACL completed.
```

 - [x] Gatling IMAP should support `IDLE`

```
27 IDLE
+ Idling
DONE
25 OK IDLE completed.
```

 - [x] Gatling IMAP should support `NOOP`

```
26 noop
26 OK NOOP completed.
```

 - [x] Gatling IMAP should support `LSUB`

```
32 lsub "" "*"
32 OK LSUB completed.
```

 - [x] Gatling IMAP should support `CLOSE`

```
96 close
96 OK CLOSE completed.
```

 - [x] Gatling IMAP should support `LOGOUT`

```
97 logout
97 OK LOGOUT completed.
```

**Comment by chibenwa** [comment]
https://github.com/linagora/gatling-imap/pull/62

**Comment by quantranhong1999** [comment]
wish list commands: https://github.com/linagora/gatling-imap/pull/63
