### ISSUE TITLE
Send a mail via SMTP without authentication

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-gatling#23]
- Re use user provisionning
- Send a mail to a local recipient of the server without authentification.
- You can write a scenario where users sends mails to each other at random, like the **JmapSendMessagesScenario**

**Comment by rouazana** [comment]
see `src/test/scala-2.12/org/apache/james/gatling/smtp/scenari/NoAuthenticationNoEncryptionScenario.scala`
