### ISSUE TITLE
Gatling should be able to create Domains and User

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-gatling#4]
Domain should be generated from a uuid.
Users and their passord from a text file.
This would allow us to use the same James server to run Gatling tests in an independant way, with multiple, different concurrent user, without having to manually provision it.

To achive this we can either consider : 
- JMX
- Docker

Actually in discussion...

**Comment by chibenwa** [comment]
Depends on #3

**Comment by mbaechler** [comment]
It's really not that useful to read users from a file when you can generate them and register them in James. 
A useful test parameter can be the number of users.

**Comment by chibenwa** [comment]
Ok from generating users, let's say from UUIDs.
Of course the plan is here to provision the ~100 -> 100K users of the test so that latest scenario can use this parameter.

**Comment by chibenwa** [comment]
I just merged the code for this issue.
