### ISSUE TITLE
Write a JMAP scenario based on a JMAP capture

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-gatling#5]
It should be multi-user.

First : 
- Authenticate
- GetMailboxes

It should then be the repetion of :
-  reading messages (GetMessageList)
- Read specific message (GetMessages)
- send a message to an other user (SetMessages)
- ...

With random waits in between.

The test should last 30 minutes.

You will determine the number of concurrent user supported for this test so that latencies keeps regular.

The different JMAP requests will be based on the traffic capture of OpenPaas INBOX

**Comment by chibenwa** [comment]
Depends on #6 #7 #3 #4

**Comment by rouazana** [comment]
Not exactly a capture, but the idea is here: #31
